e2e test:
  stage: test
  #image: mcr.microsoft.com/playwright:v1.29.0-focal
  image: node:16
  script:
    - npm ci
    - npm install
    - npx playwright install --with-deps
    - npm run test:e2e
    #- xvfb-run npm run test:e2e
  retry:
    max: 1
    when:
      - always
  artifacts:
    name: E2E Test Report
    expire_in: 1 week
    when: always
    paths:
      - reports/
    reports:
      junit: results.xml
  # tags:
  #  - "shared-macos-amd64"


